import { useRef, useState, useMemo } from 'react'
import MockBrowser from './MockBrowser.jsx'
import ApiViewer from './ApiViewer.jsx'

// An example test-execution report: metadata + per-step screenshots,
// exportable as a single combined PDF.
export default function TestReport({ tc, frameworkLabel, kind = 'web' }) {
  const isApi = kind === 'api'
  const reportRef = useRef(null)
  const [busy, setBusy] = useState(false)

  // stable "executed at" per test case
  const executedAt = useMemo(() => {
    const d = new Date()
    return d.toLocaleString('en-GB', {
      day: '2-digit', month: 'short', year: 'numeric',
      hour: '2-digit', minute: '2-digit',
    })
  }, [tc.id])

  const duration = (tc.steps.length * 0.9).toFixed(1)

  async function downloadPdf() {
    if (!reportRef.current) return
    setBusy(true)
    try {
      // load the heavy PDF libs only on demand
      const [{ default: jsPDF }, { default: html2canvas }] = await Promise.all([
        import('jspdf'),
        import('html2canvas'),
      ])
      const canvas = await html2canvas(reportRef.current, {
        scale: 2,
        backgroundColor: '#ffffff',
        useCORS: true,
      })
      const imgData = canvas.toDataURL('image/png')
      const pdf = new jsPDF('p', 'mm', 'a4')
      const pageW = pdf.internal.pageSize.getWidth()
      const pageH = pdf.internal.pageSize.getHeight()
      const imgW = pageW
      const imgH = (canvas.height * imgW) / canvas.width

      let heightLeft = imgH
      let position = 0
      pdf.addImage(imgData, 'PNG', 0, position, imgW, imgH)
      heightLeft -= pageH
      while (heightLeft > 0) {
        position -= pageH
        pdf.addPage()
        pdf.addImage(imgData, 'PNG', 0, position, imgW, imgH)
        heightLeft -= pageH
      }
      pdf.save(`Test-Report-${tc.id}.pdf`)
    } finally {
      setBusy(false)
    }
  }

  return (
    <div className="report-wrap">
      <div className="report-wrap__bar">
        <span>Test report (with screenshots)</span>
        <button className="btn btn--run" onClick={downloadPdf} disabled={busy}>
          {busy ? 'Downloading…' : 'Download'}
        </button>
      </div>

      {/* This whole block is captured into the PDF */}
      <div className="report" ref={reportRef}>
        <div className="report__head">
          <div>
            <h3 className="report__title">Test Execution Report</h3>
            <div className="report__sub">
              OrangeHRM {isApi ? 'REST API' : 'Demo'} · {frameworkLabel}
            </div>
          </div>
          <span className="report__status">PASSED</span>
        </div>

        <table className="report__meta">
          <tbody>
            <tr><th>Test Case ID</th><td>{tc.id}</td><th>Result</th><td className="ok">✔ Passed</td></tr>
            <tr><th>Title</th><td colSpan={3}>{tc.title}</td></tr>
            <tr><th>Framework</th><td>{frameworkLabel}</td><th>{isApi ? 'Client' : 'Browser'}</th><td>{isApi ? 'REST runner' : 'Chrome 124 (headless)'}</td></tr>
            <tr><th>Environment</th><td>opensource-demo.orangehrmlive.com</td><th>Executed</th><td>{executedAt}</td></tr>
            <tr><th>Total Steps</th><td>{tc.steps.length}</td><th>Duration</th><td>{duration}s</td></tr>
            <tr><th>Expected</th><td colSpan={3}>{tc.expected}</td></tr>
          </tbody>
        </table>

        <h4 className="report__h4">Steps &amp; Screenshots</h4>
        <div className="report__shots">
          {tc.steps.map((step, i) => (
            <figure className="report__shot" key={i}>
              <div className="report__shot-frame">
                {isApi
                  ? <ApiViewer state={step.state} running={false} />
                  : <MockBrowser state={step.state} running={false} />}
              </div>
              <figcaption>
                <span className="report__step-no">Step {i + 1}</span>
                {step.log}
                <span className="report__step-ok">✔</span>
              </figcaption>
            </figure>
          ))}
        </div>

        <div className="report__foot">
          Generated by QA Automation Portfolio · {frameworkLabel} · {executedAt}
        </div>
      </div>
    </div>
  )
}
